apiVersion: v1
  kind: Service
  metadata:
    name: {{ include "app.fullname" . }}
  spec:
    selector:
      app: {{ template "app.fullname" . }}
    ports:
      - protocol: TCP
        port: {{ .Values.port }}
        targetPort: {{ .Values.port }}